version: "3.8"
volumes:
  psql:
services:
  psql:
    image: postgres # this uses the 'latest' version
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678 # only do this in development
    volumes:
      - psql:/var/lib/postgresql/data # save data between restarts
    ports:
      - 5432:5432

  elysia-app:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:12345678@localhost:5432/postgres?schema=public
      - JWT_ACCESS_SECRET=OShzw5uWWhrD7cE4Uw+e5XAr+4R+uQix5UucpXbsk1o=
      - JWT_REFRESH_SECRET=f+uJBDY5ZZqleymZgN1U/d3CZrL50M3DmE+nYkWDKb0=

    expose:
      - "3000"
